<meta charset="utf-8">
<?php
echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))
        ->setSeparator(' - ')->setAutoEscape(false)
?>

<?php
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php
echo $this->headLink(array('rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/chosen.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-fix.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.4.custom.min.css');
?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/main.js')
        ->prependFile($this->basePath() . '/js/chosen.jquery.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery-ui-1.10.4.custom.min.js')
        ->prependFile($this->basePath() . '/js/jquery-2.1.0.min.js');
?>