<ul class="nav navbar-nav" id="menu">

    <?php $count = 0; ?>
    <?php foreach ($this->container as $page): ?>
        <?php //var_dump($page); exit;?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>

        <?php if (!$hasChildren): ?>
            <li <?php if ($page->isActive()) : ?> class="active" <?php endif; ?>>
                <a href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php else: ?>
            <?php foreach ($page->getPages() as $child) : ?>
                <?php
                $hasVisibleChild = FALSE;
                if ($child->isVisible()) {
                    $hasVisibleChild = TRUE;
                    break;
                }
                ?>
            <?php endforeach; ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown"
                   href="<?php echo $page->getHref() ?>"><?php
                       echo $this->translate($page->getLabel())
                       ?>
                       <?php if ($hasVisibleChild) : ?>
                        <b class="caret"></b>
                    <?php endif; ?>
                </a>

                <?php
                //только если имеет видимых детей
                if ($hasVisibleChild) :
                    ?>
                    <ul class="dropdown-menu" id="level<?php echo $count; ?>">
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php // when using partials we need to manually check for ACL conditions ?>
                            <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                            <li>
                                <a href="<?php echo $child->getHref() ?>"
                                   <?php if ($page->isActive()) : ?> class="active" <?php endif; ?>
                                   ><?php echo $this->translate($child->getLabel()) ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>

        <?php endif ?>
        <?php $count++; ?>
    <?php endforeach ?>
</ul>

<!-- фикс выпадающего меню -->
<script>
    $(document).ready(function() {
        $('.nav li.dropdown').hover(function() {
            $(this).addClass('open');
        }, function() {
            $(this).removeClass('open');
        });
    });

    $('ul.dropdown-menu [data-toggle=dropdown]').on('mouseover', function(event) {
        // Avoid following the href location when clicking
        event.preventDefault();
        // Avoid having the menu to close when clicking
        event.stopPropagation();
        // If a menu is already open we close it
        //$('ul.dropdown-menu [data-toggle=dropdown]').parent().removeClass('open');
        // opening the one you clicked on
        $(this).parent().addClass('open');

        var menu = $(this).parent().find("ul");
        var menupos = menu.offset();

        var newpos;
        if ((menupos.left + menu.width()) + 30 > $(window).width()) {
            newpos = -menu.width();
        } else {
            newpos = $(this).parent().width();
        }

        menu.css({left: newpos});

    });

    $('a.dropdown-toggle').on('click', function(event) {
        window.location = $(this).prop("href");
    });
</script>