<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>

<div class="col-md-12">
    <?php if ($myUploads) { ?>
        <h1>My Uploads</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Label</th>
                    <th>FileName</th>
                    <th>Link</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <?php foreach ($myUploads as $myUpload) { ?>
                <tr>
                    <td><?php echo $myUpload->getLabel() ?></td>
                    <td><?php echo $myUpload->getFilename() ?></td>
                    <td>
                        <a href="<?php
                        echo $this->url("uploads", array(
                            "action" => "download",
                            "id"     => $myUpload->getId()));
                        ?>">
                               <?php echo $myUpload->getFilename() ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="<?php
                            echo $this->url('uploads', array(
                                "action" => "edit",
                                "id"     => $myUpload->getId()
                            ))
                            ?>" class="btn btn-warning">Edit</a>
                            <a href="<?php
                            echo $this->url('uploads', array(
                                "action" => "delete",
                                "id"     => $myUpload->getId()
                            ))
                            ?>" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>

    <?php } ?>
</div>

<div class="col-md-12">
    <?php if ($sharedUploads) { ?>
        <h1>Shared Uploads</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Label</th>
                    <th>FileName</th>
                    <th>Link</th>
                </tr>
            </thead>
            <?php foreach ($sharedUploads as $sharedUpload) { ?>
                <tr>
                    <td><?php echo $sharedUpload->label ?></td>
                    <td><?php echo $sharedUpload->filename ?></td>
                    <td>
                        <a href="<?php
                        echo $this->url("uploads", array(
                            "action" => "download",
                            "id"     => $sharedUpload->id));
                        ?>">
                               <?php echo $sharedUpload->filename ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>

    <?php } ?>
</div>


