<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('user-manager', array(
            'action' => 'process')));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

<?php

echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
?>


<?php echo $this->form()->closeTag() ?>