<?php
//echo $form;

$title = "Add Page";

echo $this->headTitle();
?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<?php
$formRenderer = $this->formRenderer($form, 'renderer.bootstrap', 'horizontal');
$formRenderer->prepare();

echo $formRenderer->openTag($form);
?>

<?php

//if ($messages = $form->getMessages()) {
//    foreach ($messages as $message) {
//        print_r($message);
//    }
//}

?>

<fieldset class="<?php echo $formRenderer->_formStyle; ?>">

    <?php
    echo $formRenderer->formHidden($form->get("id")), "<br>";
    echo $formRenderer->formRow($form->get("title")), "<br>";
    echo $formRenderer->formRow($form->get("article")), "<br>";
    echo $formRenderer->formRow($form->get("date")), "<br>";
    echo $formRenderer->formRow($form->get("submit"));
//    echo $formRenderer->formAction($form->get('submit'));
    ?>

</fieldset>

<?php
echo $formRenderer->closeTag();
?>