<?php
//echo $form;

$title = "Edit Page";

echo $this->headTitle();
?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<?php
$form->setAttribute("action", "/page/edit/" . $id);

$formRenderer = $this->formRenderer($form, 'renderer.bootstrap', 'horizontal');
$formRenderer->prepare();

echo $formRenderer->openTag($form);
?>

<!--<div class="control-group">
    <label class="control-label" for="title">title</label>
    <div class="controls">
        <input type="text" id="title" placeholder="title">
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="article">article</label>
    <div class="controls">
        <input type="text" id="article" placeholder="article">
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="date">date</label>
    <div class="controls">
        <input type="password" id="date" placeholder="date">
    </div>
</div>
<div class="control-group">
    <div class="controls">
                <label class="checkbox">
                    <input type="checkbox"> Запомнить меня
                </label>
        <button type="submit" class="btn">submit</button>
    </div>
</div>-->

<?php
echo $formRenderer->formHidden($form->get("id")), "<br>";
echo $formRenderer->formRow($form->get("title")), "<br>";
echo $formRenderer->formRow($form->get("article")), "<br>";
echo $formRenderer->formRow($form->get("date")), "<br>";
echo $formRenderer->formRow($form->get("submit"));

echo $formRenderer->closeTag();
?>