<h1>Hi there.</h1>

<!--<pre>
<?php
//print_r($pages);

$title = "Страницы";
$this->headTitle($title);
?>
</pre>-->

<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>

<a href="/page/add">Добавить</a>
<table class="table">
    <thead>
    <th>Название</th>
    <th>Дата</th>
    <th>Содержание</th>
    <th>&nbsp;</th>
</thead>
<tbody>
    <?php foreach ($pages as $page) : ?>
        <tr>
            <td><?= $page->title ?></td>
            <td><?= $page->date ?></td>
            <td><?= $page->article ?></td>
            <td>
                <a href="<?php
                echo $this->url("page", array(
                    "action" => "edit",
                    "id"     => $page->id,
                ))
                ?>
                   ">Редактировать</a>
                <a href="<?php
                echo $this->url("page", array(
                    "action" => "delete",
                    "id"     => $page->id,
                ))
                ?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</tbody>
</table>
