<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <?php
        echo $this->partial("partial/head", "default");
        ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                    <div class="container">
                        <div class="navbar-inner navbar-collapse">

                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle"
                                        data-toggle="collapse"
                                        data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#">zend2 tutorial</a>
                            </div>

                            <?php $partial = array('partial/top_menu.phtml', 'default') ?>
                            <?php
                            echo $this->navigation("index_navigation")
                                    ->menu()
                                    ->setMinDepth(0)
                                    ->setMaxDepth(0)
                                    ->setUlClass('nav navbar-nav')
                                    ->setPartial($partial);
                            ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <?php
                echo $this->navigation('index_navigation')
                        ->breadcrumbs()->setMinDepth(0)
                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'))
                        ->setRenderInvisible(true);
                ?>
            </div>

            <div class="row content">
                <?php echo $this->content; ?>
                <hr>
            </div>

            <div class="row">
                <footer>
                    <p>&copy; <?php echo date('Y') ?> by Razlet.RU
                        <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>

            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
