<section class="upload">
    <h2><?php echo $this->escapeHtml($upload->getLabel()); ?></h2>
    <h4><?php echo $this->escapeHtml($upload->getFilename()); ?></h4>

    <img src="<?php
    echo $this->url('media', array('action'    => 'showImage',
        'id'        => $upload->getId(),
        'subaction' => 'full'));
    ?>" />
</section>

<a href="<?php echo $this->url('media'); ?>">
    &raquo; Show Gallery</a>