<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
));

//$formRenderer = $this->formRenderer($form, 'renderer.bootstrap', 'horizontal');
//$formRenderer->prepare();
//
//echo $formRenderer->openTag($form);
//echo $formRenderer->formRow($form->get("username")) . "<br>";
//echo $formRenderer->formRow($form->get("password")) . "<br>";
//echo $formRenderer->formRow($form->get("rememberme")) . "<br>";
//echo $formRenderer->formCollection($form);
//echo $formRenderer->closeTag();

$form->prepare();

echo $this->form()->openTag($form) . "<br>";
echo $this->formRow($form->get("username")) . "<br>";
echo $this->formRow($form->get("password")) . "<br>";
echo $this->formRow($form->get("rememberme")) . "<br>";
?>

<?php if ($contracts) : ?>
    <label for="contracts">Выберите договор</label>

    <select name="contracts" id="contracts">
        <?php
        foreach ($contracts as $id => $name) {
            echo "<option value='$id'>$name</option>";
        }
        ?>
    </select>
    <br>

    <?php
endif;
?>

<?php
echo $this->formSubmit($form->get("submit")) . "<br>";
//echo $this->formCollection($form) . "<br>";
echo $this->form()->closeTag();

if ($this->messages) {
    echo '<ul>';
    foreach ($this->messages as $message) {
        echo '<li>' . $message . '</li>';
    }
    echo '</ul>';
}
