<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
));
$form->setAttribute("role", "form");

$formRenderer = $this->formRenderer($form, 'renderer.bootstrap', 'horizontal');
$formRenderer->prepare();

echo $formRenderer->openTag($form);
echo $formRenderer->formRow($form->get("username")) . "<br>";
echo $formRenderer->formRow($form->get("password")) . "<br>";
echo $formRenderer->formRow($form->get("rememberme")) . "<br>";
echo $formRenderer->formRow($form->get("submit")
                ->setAttribute('class', 'btn btn-primary')) . "<br>";
//echo $formRenderer->formCollection($form);
echo $formRenderer->closeTag();

if ($this->messages) {

    foreach ($this->messages as $message) {
        echo '<div class="alert alert-warning">' . $message . '</div>';
    }
}
