<?php
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
));
$form->prepare();

echo $this->form()->openTag($form->setAttribute("role", "form")) . "<br>";
?>
<div class = "form-group">
    <?php
    echo $this->formRow($form->get("username")
                    ->setAttribute("class", "form-control")) . "<br>";
    ?>
</div>
<div class = "form-group">
    <?php
    echo $this->formRow($form->get("password")
                    ->setAttribute("class", "form-control")) . "<br>";
    ?>
</div>
<div class="checkbox">
    <label>
        <?php
        echo $this->formRow($form->get("rememberme")) . "<br>";
        ?>
    </label>
</div>

<?php if ($contracts) : ?>
    <label for="contracts">Выберите договор</label>

    <select name="contracts" id="contracts">
        <?php
        foreach ($contracts as $id => $name) {
            echo "<option value='$id'>$name</option>";
        }
        ?>
    </select>
    <br>

    <?php
endif;
?>

<?php
echo $this->formSubmit($form->get("submit")
                ->setAttribute('class', 'btn btn-primary')) . "<br>";
//echo $this->formCollection($form) . "<br>";
echo $this->form()->closeTag();

if ($this->messages) {

    foreach ($this->messages as $message) {
        echo '<div class="alert alert-warning">' . $message . '</div>';
    }
}
