<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
));

//$formRenderer = $this->formRenderer($form, 'renderer.bootstrap', 'horizontal');
//$formRenderer->prepare();
//
//echo $formRenderer->openTag($form);
//echo $formRenderer->formCollection($form);
//echo $formRenderer->closeTag();

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

if ($this->messages) {
    echo '<ul>';
    foreach ($this->messages as $message) {
        echo '<li>' . $message . '</li>';
    }
    echo '</ul>';
}
?>