<div class="jumbotron">
    <h1>
        <?php echo sprintf('Welcome to %sSED%s', '<span class="zf-green">', '</span>')
        ?>
    </h1>
    <p>
    </p>
    <p>
        <?php
        $store    = new \Auth\Model\AuthStorage("auth_storage");
        $username = $store->read();

        if ($username) {
            echo '<a class="btn btn-success btn-lg" '
            . 'href="' . $this->url("login/process", array(
                "action" => "logout"))
            . '">' . $this->translate('Выйти') . "</a>";
        }
        else {
            echo '<a class="btn btn-success btn-lg" '
            . 'href="' . $this->url("login/process", array(
                "action" => "login"))
            . '">' . $this->translate('Войти') . "</a>";
        }
        ?>

    </p>
</div>
